// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbyuxrtjtftajwsiazcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieXV4cnRqdGZ0YWp3c2lhemNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Njc2NjIsImV4cCI6MjA2MzI0MzY2Mn0.jCrCPY3Y0LXHuix81yTMuW1B94toggMH5rTBK-PTvX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);